export const FETCH_POSTS_REQUEST = 'FETCH_POSTS_REQUEST';
export const FETCH_POSTS_SUCCESS = 'FETCH_POSTS_SUCCESS';
export const FETCH_POSTS_FAILED = 'FETCH_POSTS_FAILED';

export const FETCH_CATEGORIES_POSTS_REQUEST = 'FETCH_CATEGORIES_POSTS_REQUEST';
export const FETCH_CATEGORIES_POSTS_SUCCESS = 'FETCH_CATEGORIES_POSTS_SUCCESS';
export const FETCH_CATEGORIES_POSTS_FAILED = 'FETCH_CATEGORIES_POSTS_FAILED';

export const FETCH_POST_REQUEST = 'FETCH_POST_REQUEST';
export const FETCH_POST_SUCCESS = 'FETCH_POST_SUCCESS';
export const FETCH_POST_FAILED = 'FETCH_POST_FAILED';

export const FETCH_POST_COMMENTS_REQUEST = 'FETCH_POST_COMMENTS_REQUEST';
export const FETCH_POST_COMMENTS_SUCCESS = 'FETCH_POST_COMMENTS_SUCCESS'; 
export const FETCH_POST_COMMENTS_FAILED = 'FETCH_POST_COMMENTS_FAILED';

export const FETCH_USER_REQUEST = 'FETCH_USER_REQUEST';
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS';
export const FETCH_USER_FAILED = 'FETCH_USER_FAILED';

export const SIGN_IN_REQUEST = 'SIGN_IN_REQUEST';
export const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS';
export const SIGN_IN_FAILED = 'SIGN_IN_FAILED';

export const SIGN_OUT_SUCCESS = 'SIGN_OUT_SUCCESS';

export const SIGN_UP_REQUEST = 'SIGN_UP_REQUEST';
export const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS';
export const SIGN_UP_FAILED = 'SIGN_UP_FAILED';

export const FETCH_CURRENT_USER_REQUEST = 'FETCH_CURRENT_USER_REQUEST';
export const FETCH_CURRENT_USER_SUCCESS = 'FETCH_CURRENT_USER_SUCCESS';
export const FETCH_CURRENT_USER_FAILED = 'FETCH_CURRENT_USER_FAILED';

export const FOLLOW_USER_REQUEST = 'FOLLOW_USER_REQUEST';
export const FOLLOW_USER_SUCCESS = 'FOLLOW_USER_SUCCESS';
export const FOLLOW_USER_FAILED = 'FOLLOW_USER_FAILED';

export const UNFOLLOW_USER_REQUEST = 'UNFOLLOW_USER_REQUEST';
export const UNFOLLOW_USER_SUCCESS = 'UNFOLLOW_USER_SUCCESS';
export const UNFOLLOW_USER_FAILED = 'UNFOLLOW_USER_FAILED';

export const GIVE_KUDOS_REQUEST = 'GIVE_KUDOS_REQUEST';
export const GIVE_KUDOS_SUCCESS = 'GIVE_KUDOS_SUCCESS'; 
export const GIVE_KUDOS_FAILED = 'GIVE_KUDOS_FAILED';

export const REMOVE_KUDOS_REQUEST = 'REMOVE_KUDOS_REQUEST';
export const REMOVE_KUDOS_SUCCESS = 'REMOVE_KUDOS_SUCCESS'; 
export const REMOVE_KUDOS_FAILED = 'REMOVE_KUDOS_FAILED';

export const UPDATE_USER_DETAILS_REQUEST = 'UPDATE_USER_DETAILS_REQUEST';
export const UPDATE_USER_DETAILS_SUCCESS = 'UPDATE_USER_DETAILS_SUCCESS'; 
export const UPDATE_USER_DETAILS_FAILED = 'UPDATE_USER_DETAILS_FAILED';

export const UPDATE_USER_AVATAR_REQUEST = 'UPDATE_USER_AVATAR_REQUEST';
export const UPDATE_USER_AVATAR_SUCCESS = 'UPDATE_USER_AVATAR_SUCCESS'; 
export const UPDATE_USER_AVATAR_FAILED = 'UPDATE_USER_AVATAR_FAILED';

export const UPDATE_USER_PASSWORD_REQUEST = 'UPDATE_USER_PASSWORD_REQUEST';
export const UPDATE_USER_PASSWORD_SUCCESS = 'UPDATE_USER_PASSWORD_SUCCESS';
export const UPDATE_USER_PASSWORD_FAILED = 'UPDATE_USER_PASSWORD_FAILED';

export const CREATE_POST_REQUEST = 'CREATE_POST_REQUEST';
export const CREATE_POST_SUCCESS = 'CREATE_POST_SUCCESS';
export const CREATE_POST_FAILED = 'CREATE_POST_FAILED'; 

export const EDIT_POST_REQUEST = 'EDIT_POST_REQUEST';
export const EDIT_POST_SUCCESS = 'EDIT_POST_SUCCESS'; 
export const EDIT_POST_FAILED = 'EDIT_POST_FAILED';

export const GET_PASSWORD_RESET_EMAIL_REQUEST = 'GET_PASSWORD_RESET_EMAIL_REQUEST';
export const GET_PASSWORD_RESET_EMAIL_SUCCESS = 'GET_PASSWORD_RESET_EMAIL_SUCCESS';
export const GET_PASSWORD_RESET_EMAIL_FAILED = 'GET_PASSWORD_RESET_EMAIL_FAILED'; 

export const SET_NEW_PASSWORD_REQUEST = 'SET_NEW_PASSWORD_REQUEST';
export const SET_NEW_PASSWORD_SUCCESS = 'SET_NEW_PASSWORD_SUCCESS';
export const SET_NEW_PASSWORD_FAILED = 'SET_NEW_PASSWORD_FAILED';

export const REPLY_TO_POST_REQUEST = 'REPLY_TO_POST_REQUEST';
export const REPLY_TO_POST_SUCCESS = 'REPLY_TO_POST_SUCCESS';
export const REPLY_TO_POST_FAILED = 'REPLY_TO_POST_FAILED';

export const REPLY_TO_COMMENT_REQUEST = 'REPLY_TO_COMMENT_REQUEST';
export const REPLY_TO_COMMENT_SUCCESS = 'REPLY_TO_COMMENT_SUCCESS';
export const REPLY_TO_COMMENT_FAILED = 'REPLY_TO_COMMENT_FAILED';

export const DELETE_COMMENT_REQUEST = 'DELETE_COMMENT_REQUEST';
export const DELETE_COMMENT_SUCCESS = 'DELETE_COMMENT_SUCCESS';
export const DELETE_COMMENT_FAILED = 'DELETE_COMMENT_FAILED';

export const EDIT_COMMENT_REQUEST = 'EDIT_COMMENT_REQUEST';
export const EDIT_COMMENT_SUCCESS = 'EDIT_COMMENT_SUCCESS';
export const EDIT_COMMENT_FAILED = 'EDIT_COMMENT_FAILED';

export const UPDATE_CATEGORY_POST_IDS = 'UPDATE_CATEGORY_POST_IDS'; 




// Error related actions

export const CLEANSE_ERRORS = 'CLEANSE_ERRORS';

export const EMAIL_NOT_FOUND_ERROR_REGISTER = 'EMAIL_NOT_FOUND_ERROR_REGISTER';
export const EMAIL_NOT_FOUND_ERROR_ACKNOWLEDGE = 'EMAIL_NOT_FOUND_ERROR_ACKNOWLEDGE';



// Success related actions

export const CLEANSE_SUCCESSES = 'CLEANSE_SUCCESSES';

export const PASSWORD_RESET_EMAIL_SENT_REGISTER = 'PASSWORD_RESET_EMAIL_SENT_REGISTER';
export const PASSWORD_RESET_EMAIL_SENT_ACKNOWLEDGE = 'PASSWORD_RESET_EMAIL_SENT_ACKNOWLEDGE';











 